return function()
  return {
    Primary = {
      "Sawn Off Shotgun",
      "Ruger 10/22",
      "Ingram MAC-10",
      "Sten Mk V",
      "Mossberg 500",
      "Aero Survival Rifle",
      "Winchester Model 70",
      "KAC PDW",
      "PP-91 Kedr",
      "SAP-6",
      "Kriss Vector",
      "M1 Garand",
      "MP5A2",
      "AR-57",
      "P90",
      "M4A1",
      "SKO Shorty",
      "M14",
      "AK-47",
      "Mosin Nagant",
      "CMMG Mk47 Mutant",
      "RPK",
      "LWRC IC-PSD",
      "Flamethrower",
      "M60",
      "Barrett M82A1",
      "Winchester Model 1892",
    },
    Secondary = {
      "Glock 17",
      "LH9 MKII",
      "Walther P38",
      "Serbu Super Shorty",
      "M1911A1",
      "Makarov",
      "TEC-9",
      "MP-443 Grach",
      "PB 6P9",
      "Uzi",
      "Taurus Model 66",
      "CBJ-MS",
      "Colt Python",
      "HK P30L",
      "Desert Eagle"
    },
    Melee = {
      "2x4",
      "Wrench",
      "Frying Pan",
      "Umbrella",
      "Crowbar",
      "Pool Cue",
      "Shovel",
      "Golf Club",
      "Butcher Knife",
      "2x4 w/ Barbed Wire",
      "Sledge Hammer",
      "Baseball Bat",
      "Fire Axe",
      "Spiked Baseball Bat",
      "Sabre",
      "Katana"
    }
  }
end